version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "00:00"
    allow:
      - dependency-name: "simple-icons"
    reviewers:
      - "diegoliv"