name: Auto Update Simple Icons
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            repository: ${{ github.repository }}
            ref: ${{ github.ref }}
            fetch-depth: 0
      - name: Use Node v20
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Compare release versions
        id: get-releases
        run: |
          simple_icons_version="$(curl --retry 5 -s https://api.github.com/repos/simple-icons/simple-icons/releases/latest | jq -r .tag_name)"
          echo "si=$simple_icons_version" >> $GITHUB_OUTPUT
          echo "lib=$(cat package.json | grep '"version":' | cut -d'"' -f4)" >> $GITHUB_OUTPUT
      - name: Bump Version
        if: steps.get-releases.outputs.lib != steps.get-releases.outputs.si
        run: |
          # Update versions in package.json
          sed -i 's/"version": "${{ steps.get-releases.outputs.lib }}",/"version": "${{ steps.get-releases.outputs.si }}",/' package.json
          sed -i 's/"simple-icons": "${{ steps.get-releases.outputs.lib }}"/"simple-icons": "${{ steps.get-releases.outputs.si }}"/' package.json
          # Update version in README
          sed -i 's/${{ steps.get-releases.outputs.lib }}/${{ steps.get-releases.outputs.si }}/g' README.md
      - name: Install Dependencies
        if: steps.get-releases.outputs.lib != steps.get-releases.outputs.si
        id: install-dependencies
        run: |
          npm install
      - name: Build app
        if: steps.get-releases.outputs.lib != steps.get-releases.outputs.si
        run: npm run build-vite
      - name: Commit
        if: steps.get-releases.outputs.lib != steps.get-releases.outputs.si
        uses: EndBug/add-and-commit@v9
        with:
          add: 'package.json README.md'
          default_author: github_actions
          message: "-m 'Version Bump to ${{steps.get-releases.outputs.si}}'"
          tag: "-a ${{steps.get-releases.outputs.si}}"
      - name: Create GitHub release
        if: steps.get-releases.outputs.lib != steps.get-releases.outputs.si
        id: create-release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get-releases.outputs.si }}
          release_name: Release ${{ steps.get-releases.outputs.si }}
          body: |
            See https://github.com/simple-icons/simple-icons/releases/tag/${{ steps.get-releases.outputs.si }}
      - name: Create Release Asset
        uses: vimtor/action-zip@v1.1
        with:
          files: dist/
          dest: ${{steps.get-releases.outputs.si}}.zip
      - uses: shogo82148/actions-upload-release-asset@v1
        name: Upload Release Asset
        if: steps.get-releases.outputs.lib != steps.get-releases.outputs.si
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ${{steps.get-releases.outputs.si}}.zip